### ISSUE TITLE
List of function for p-mvc

### ISSUE THREAD

**Issue by perryfaro** [p-mvc/p-mvc#1]
Model
- [x] model::load

View
- [x] view::css
- [x] view::js
- [x] view::json
- [x] view::load

Data
- [x] data::get
- [x] data::post
- [x] data::pre
- [x] data::session
- [x] data::type

Format
- [x] format::toArray
- [x] format::toFloat
- [x] format::toInt
- [x] format::toJson
- [ ] format::toObject (to-do)
- [x] format::toString

File
- [ ] file::append (to-do)
- [x] file::clear
- [ ] file::create (to-do)
- [x] file::extension
- [x] file::get
- [x] file::isFile
- [x] file::size
- [ ] file::write (to-do)

Folder
- [x] folder::clear
- [ ] folder::create (to-do)
- [x] folder::get
- [ ] folder::permissions (to-do?)
- [x] folder::isFolder
- [ ] folder::size (to-do)

Date
- [x] date::difference
- [x] date::format
- [x] date::now
- [x] date::isDate

Text
- [x] text::contains
- [x] text::hash
- [x] text::length
- [x] text::loremIpsum
- [x] text::lowercase
- [x] text::replace
- [x] text::strip
- [x] text::substring
- [x] text::uppercase

Number
- [x] number::average
- [x] number::max
- [x] number::min
- [x] number::percentage
- [x] number::random
- [x] number::round
- [x] number::total

Validate
- [x] validate::isArray
- [x] validate::isBool
- [ ] validate::isDate (to-do)
- [x] validate::isEmail
- [ ] validate::isFloat (to-do)
- [ ] validate::isInt (to-do)
- [x] validate::isIp
- [x] validate::isJson
- [x] validate::length
- [ ] validate::isObjrct (to-do)
- [ ] validate::isString (to-do)
- [x] validate::isType

## todo 

Create specification of function this list below
- Config
- Database
- Client
- Url
- Session
- Chache
